version: "2"

linters:
  enable:
    - errcheck
    - wrapcheck
    - govet
    - ineffassign
    - staticcheck
    - goconst
    - gocyclo
    - misspell
    - whitespace
    - nolintlint
  settings:
    gocyclo:
      min-complexity: 15
  exclusions:
    paths:
      - tmp
      - cmd
      - e2e_test\.go

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - tmp
      - cmd
      - e2e_test\.go
